version: '3.4'
services:
  backend:
    build: ../backend
    ports:
      - "8000:8000"
    env_file:
      ../.env
    depends_on:
      - postgres
    command: >
      sh -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
  postgres:
      image: postgres:11.5-alpine
      container_name: postgres
      environment:
        - POSTGRES_USER=hello_django
        - POSTGRES_PASSWORD=hello_django
        - POSTGRES_DB=hello_django_dev
        - PGDATA=/var/lib/postgresql/data/
      ports:
        - "5432:5432"
      volumes:
        - .docker-volumes/postgres/data:/var/lib/postgresql/data/"